name: safe_config
description: A safe and convenient way to read YAML configuration files.
version: 3.0.0-b2
author: stable|kernel <jobs@stablekernel.com>
homepage: http://stablekernel.com
documentation:

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  runtime:
    git: https://github.com/j4qfrost/dart-runtime.git

dev_dependencies:
  test: ^1.16.4