name: safe_config
description: A safe and convenient way to read YAML configuration files.
version: 3.0.0
author: stable|kernel <jobs@stablekernel.com>
homepage: http://stablekernel.com
documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  yaml: '>=2.1.8 <3.0.0'
  runtime:
    path: /Users/joeconway/Projects/runtime

dev_dependencies:
  test: ^1.3.0
