name: safe_config
description: A safe and convenient way to read YAML configuration files.
version: 1.2.2
author: Joe Conway <joe.conway@stablekernel.com>
homepage: http://stablekernel.com
documentation:

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  yaml: '>=2.1.8 <3.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
